export const HTTP_METHOD_GET = 'HTTP_METHOD_GET'
export const HTTP_METHOD_POST = 'HTTP_METHOD_POST'
export const HTTP_METHOD_PUT = 'HTTP_METHOD_PUT'
export const HTTP_METHOD_DELETE = 'HTTP_METHOD_DELETE'

export const HTTP_METHODS_TO_EXPRESS_FUNCTIONS = {
	[HTTP_METHOD_GET]: 'get',
	[HTTP_METHOD_POST]: 'post',
	[HTTP_METHOD_PUT]:  'put',
	[HTTP_METHOD_DELETE]: 'delete'
}
